version: "3.8"

services:
  backend:
    build:
     dockerfile: backend/Dockerfile
     context: .
    ports:
      - "8000:8000"
    # environment:
    #   - PYTHONPATH=/app/backend
    env_file:
      - backend/.env
    volumes:
      - ./backend/data:/app/data  # Persist FAISS index across container restarts
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
